### ISSUE TITLE
SQL Fehler bei Newsletter Versand

### ISSUE THREAD

**Issue by reluem** [terminal42/contao-news_newsletter#4]
Beim Versuch, die Nachrichten an bestätigte Abonnenten zu versenden, kommt leider folgender Fehler:

>  PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 (SELECT id, name AS value FROM tl_member_group WHERE id IN ())' thrown in /is/htdocs/xx/www/xx/system/modules/core/library/Contao/Database/Statement.php on line 295

Andere Newsletter ohne News funktionieren weiterhin.
Contao 3.5.24 mit PHP 7.0.16-he.0

**Comment by qzminski** [comment]
@terminal42/pilots I had exactly the same issue in my extension. There are basically two problems with formatting all available model data using `Haste\Util\Format`:

1. The `options_callback` field setting may require the `DataContainer` object which is often not available.
2. If the `foriegnKey` field settings is present but no value was given it results in an error presented above. Maybe we should provide the `0` value instead.

To workaround those problem I have did some dirty tricks, see here: https://github.com/codefog/contao-events_subscriptions/commit/e173111d0e66572d066279b00a1aa62cb26a1806

Maybe we should fix it in the Haste though?

**Comment by Xendiadyon** [comment]
I guess you correctly identified the problem. However, I don't understand your solution.

So I guess that Haste should indeed be fixed :(

**Comment by qzminski** [comment]
@Xendiadyon likely yes but I am waiting for other contributors to provide some feedback.

**Comment by netzarbeiter** [comment]
I came across the same problem with the query error, how can I help to get things done?

**Comment by Xendiadyon** [comment]
Dirty Hack, von dem ich nicht weiß, ob der jetzt zuverlässig funktioniert oder ob er weitere Probleme verursacht (Umsetzung nur auf eigene Gefahr)

Es gibt Probleme mit dem übergebenen Objekt in der Erweiterung "haste" (Grundlage für quasi alles).

Der Workaround in /www/htdocs/system/modules/haste/library/Haste/Util/Format.php: wenn "varValue" leer ist, setze "0" in der MySQL-Abfrage (Z.152-155).
Wenn das "objDc" nicht übergeben ist (Z.140,145), führe die Abfragen nicht aus.

![image](https://cloud.githubusercontent.com/assets/2657385/23909609/7de23b82-08d7-11e7-855e-b5a9a5097676.png)

**Comment by Toflar** [comment]
> The options_callback field setting may require the DataContainer object which is often not available.

Which is not an issue of haste, right?


> If the foriegnKey field settings is present but no value was given it results in an error presented above. Maybe we should provide the 0 value instead.

Yeah, this issue should be fixable by turning this

```php
$objOptions = \Database::getInstance()->query("SELECT id, " . $chunks[1] . " AS value FROM " . $chunks[0] . " WHERE id IN (" . implode(',', array_map('intval', (array) $varValue)) . ")");
```

into this:

```php
$ids = 0 === count((array) $varValue) : [0] : (array) $varValue;
$objOptions = \Database::getInstance()->query("SELECT id, " . $chunks[1] . " AS value FROM " . $chunks[0] . " WHERE id IN (" . implode(',', array_map('intval', $ids)) . ")");
```

**Comment by qzminski** [comment]
> Which is not an issue of haste, right?

Not the Haste issue but since we are providing this utility we should handle that case I think. In most of the cases you need just a `DataContainer` mockup which contains basic data such as id, table name and the active record data. That we can do imo by providing an extra method to mockup this object and then developer can decide whether to use it or not.

**Comment by Toflar** [comment]
Imho the `options_callback` is a whole different story and it's not related to haste at all. You can pass it if you like. It's not haste's responsibility.
The original issue should be fixed with my code, did anyone test this?

**Comment by Xendiadyon** [comment]
but haste should not throw an error if the options_callback is not passed?

**Comment by Toflar** [comment]
Haste doesn't throw an error? The initial error in this issue should be fixed with my piece of code, please test this.

**Comment by netzarbeiter** [comment]
Used this:
```
$ids = 0 === count((array) $varValue) : [0] : (array) $varValue;
$objOptions = \Database::getInstance()->query("SELECT id, " . $chunks[1] . " AS value FROM " . $chunks[0] . " WHERE id IN (" . implode(',', array_map('intval', $ids)) . ")");
```
Error:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected ':' at /home/username/public_html/domain.ch/vendor/codefog/contao-haste/library/Haste/Util/Format.php:150)"} []`

Used this:
```
$ids = 0 === count((array) $varValue) ? [0] : (array) $varValue;
$objOptions = \Database::getInstance()->query("SELECT id, " . $chunks[1] . " AS value FROM " . $chunks[0] . " WHERE id IN (" . implode(',', array_map('intval', $ids)) . ")");
```
Error:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to tl_news_archive_newsletter::getNotificationChoices() must be an instance of Contao\\DataContainer, null given, called in /home/user/public_html/domain.ch/vendor/codefog/contao-haste/library/Haste/Util/Format.php on line 142 at /home/user/public_html/domain.ch/vendor/terminal42/contao-news_newsletter/dca/tl_news_archive.php:65)"} []`

**Comment by qzminski** [comment]
Try this:
```php
$ids = $varValue ? (array) $varValue : [0];
```

**Comment by netzarbeiter** [comment]
Used this:
```
$ids = $varValue ? (array) $varValue : [0];
$objOptions = \Database::getInstance()->query("SELECT id, " . $chunks[1] . " AS value FROM " . $chunks[0] . " WHERE id IN (" . implode(',', array_map('intval', $ids)) . ")");
```
Same error:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to tl_news_archive_newsletter::getNotificationChoices() must be an instance of Contao\\DataContainer, null given, called in /home/user/public_html/domain.ch/vendor/codefog/contao-haste/library/Haste/Util/Format.php on line 142 at /home/user/public_html/domain.ch/vendor/terminal42/contao-news_newsletter/dca/tl_news_archive.php:65)"} []`

**Comment by qzminski** [comment]
Ah sorry, did not look at the error message 😄  that line is irrelevant, the error you are getting refers to the `DataContainer` problem.

**Comment by Toflar** [comment]
So @qzminski would you provide a dc wrapper or what's your idea?

**Comment by qzminski** [comment]
I opt for a workaround from my other project:

codefog/contao-events_subscriptions@e173111

**Comment by Toflar** [comment]
Well, I guess it would work for most cases but at the same time it's also dangerous somehow :)

**Comment by qzminski** [comment]
It is indeed, yet I can't think of other solution really. This mock would be passed only and only to the `options_callback` anyway and I highly doubt anyone would call some method from it.

**Comment by qzminski** [comment]
For further discussion and hotfix please see https://github.com/codefog/contao-haste/issues/101.

I will let this task open however to bump the necessary dependencies in the `composer.json` file later on.

**Comment by reluem** [comment]
seems to be working now! Issue can be closed.
