### ISSUE TITLE
Suggestion: News collection

### ISSUE THREAD

**Issue by SpeGal** [terminal42/contao-news_newsletter#7]
I would like to suggest a feature that would help us a lot: Coud this extension be adapted so that a setting is awailable that allowes to not sent the newsletter when just one news article is posted but e.g. three, four, five ... I mean a setting where I can say: Don't send the newsletter right away, wait until there are several new articles and then send it (still automated).

We publish a new news article every second day but cannot "spam" our clients with a new email so often. So we would rather have one email a week or even every other week that shows a teaser of all the latest news so that our clients can decide about which topic they want to read more details.

Could this be implemented?

**Comment by aschempp** [comment]
I'm not sure if that's what this extension is about, so I don't think we'll add this anytime soon "for free".. But if you have a developer at hand to implement this, a pull request is always welcome.
https://www.terminal42.ch/en/open-source.html
